### ISSUE TITLE
Consul read-only allows creating/updating keys

### ISSUE THREAD

**Issue by dsolsona** [jippi/hashi-ui#332]
Hi,

This is for hashi-ui version 0.20.1 

I have started playing around with the Consul integration and it seems that you can create/update keys in the Consul KV but not delete the keys.

```
Sep 26 01:57:31 server1 hashi-ui[23444]: time="2017-09-26T01:57:31-05:00" level=error msg="Can not execute /consul/kv/delete?key=test/deleteme: hashi-ui is in read-only mode" connection_id=b16d50c3
```

I'd expect to not be able to create/update any keys in read-only mode. 

What I can't tell you if this used to work before.

**Comment by jippi** [comment]
Should be fixed in master now, a new docker build should be up in a few minutes in `latest` - let me know if it fixes the issue and I'll cut a new release

**Comment by dsolsona** [comment]
Hi,

Sorry for the delay in getting back to you. I just went and downloaded your latest release 0.21.2 and it seems this is still happening.

Starting hashi-ui shows that consul is in read-only mode

> Oct 10 00:42:14 server1 hashi-ui[26645]: time="2017-10-10T00:42:14-05:00" level=info msg="| consul-read-only     : Yes

In the UI I can still create new keys in the KV, edit existing ones but I can't delete any.

**Comment by jippi** [comment]
Fixed in master, sorry about that
